before:
  hooks:
    - go mod download
builds:
  - main: cmd/tiarraview/main.go
    binary: tiarraview
    flags:
      - -tags=fts5
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
